config/routes.rb
Rails.application.routes.draw do
  resources :workshops, shallow: true do
    resources :timeslots, shallow: true do
      resources :bookings
    end
  end
  devise_for :users

  get "instructor", to: "workshops#instructor"
  get "sales", to: "bookings#sales"
  get "purchases", to: "bookings#purchases"

  root "workshops#index"
end

app/models/workshop.rb
class Workshop < ApplicationRecord
  validates :title, :description, :category, :skill_level, :location, presence: true

  belongs_to :user
  has_many :timeslots, dependent: :destroy
  has_one_attached :img
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :eager_load
  before_action :set_workshop, only: %i[ show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :check_auth, except: %i[new index create show instructor]

  def instructor
    # select workshops that belong to the curent user
    @workshops = Workshop.where(user: current_user)
  end

  # GET /workshops or /workshops.json
  def index
    # select all workshops
    @workshops = Workshop.all.order(created_at: :desc)
  end
  
  def show
    # select timeslots that belong to the current workshop
    @timeslots = Timeslot.where("workshop_id = ?", @workshop.id).order(day: :asc)
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  # GET /workshops/1/edit
  def edit
  end

  # POST /workshops or /workshops.json
  def create
    @workshop = Workshop.new(workshop_params)
    @workshop.user_id = current_user.id
    authorize(@workshop)

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to new_workshop_timeslot_path(@workshop.id), notice: "Workshop was successfully created." }
        format.json { render :new }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workshops/1 or /workshops/1.json
  def update
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to workshop_url(@workshop), notice: "Workshop was successfully updated." }
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1 or /workshops/1.json
  def destroy
    @workshop.destroy

    respond_to do |format|
      format.html { redirect_to workshops_url, notice: "#{@workshop.title} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.includes(:user, :timeslots)
      @workshop = Workshop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workshop_params
      params.require(:workshop).permit(:user_id, :title, :price, :description, :category, :skill_level, :location, :img)
    end

    def check_auth
      authorize(@workshop)
    end

    #eager load associations 
    def eager_load
      @timeslots = Timeslot.includes(:workshop)
      @workshops = Workshop.includes(:user)
    end
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_edit_form.html.erb
<%= form_with(model: workshop) do |form| %>
  <% if workshop.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>

      <ul>
        <% workshop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="mb-3">
    <%= form.label :title, class:"form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class:"form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :category, class:"form-label" %>
    <%= form.select :category, ['MOBA', 'FPS', 'MMORPG','RTS'], class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :skill_level, class:"form-label" %>
    <%= form.select :skill_level, ['Beginner', 'Average', 'Expert'], class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :location, class:"form-label" %>
    <%= form.text_area :location, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :img, class:"form-label" %>
    <%= form.file_field :img, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Save", class:"btn btn-primary" %>
  </div>
    <%= link_to "Back", @workshop, class: "mb-3 btn btn-primary" %> 
    <%= link_to "See all workshops", workshops_path, class: "mb-3 btn btn-primary" %>
<% end %>

app/views/workshops/_form.html.erb
<%= form_with(model: workshop) do |form| %>
  <% if workshop.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>

      <ul>
        <% workshop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="mb-3">
    <%= form.label :title, class:"form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class:"form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :location, class:"form-label" %>
    <%= form.text_area :location, class: "form-control" %>
  </div>
  
  <div class="mb-3">
    <%= form.label :category, class:"form-label" %>
    <%= form.select :category, ['MOBA', 'FPS', 'MMORPG', 'RTS'], class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :skill_level, class:"form-label" %>
    <%= form.select :skill_level, ['Beginner', 'Average', 'Expert'], class: "form-control" %>
  </div>


  <div class="mb-3">
    <%= form.label :img, class:"form-label" %>
    <%= form.file_field :img, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Save and proceed to add time slots", class:"btn btn-primary" %>
  </div>

  <%= link_to "Back to workshops", workshops_path, class:"btn btn-primary"  %>

<% end %>

app/views/workshops/_workshop.html.erb
<div class="card mb-3 mt-3" id="<%= dom_id workshop %>">
  <div class="d-flex mt-2 ms-2 gap-1">
    <p class="badge rounded-pill bg-primary"><%= workshop.category %></p>
    <p class="badge rounded-pill bg-primary"><%= workshop.skill_level %></p>
  </div>
  <div class="d-flex justify-content-center">
      <% if workshop.img.attached? %>
        <%= cl_image_tag(workshop.img.key, crop: :scale, width: 200, cloud_name: ENV['CLOUDINARY_CLOUD_NAME'])%>
      <% else %>
        <%= cl_image_tag("palceholder_nwndnl.png", crop: :scale, width: 200, cloud_name: ENV['CLOUDINARY_CLOUD_NAME'])%>
      <% end %>
  </div>
  <div class="card-body p-4">
    <h5 class="card-title"><%= workshop.title %></h5>
    <p class="card-text"><%= "Instructor: #{workshop.user.full_name}" %></p>
    <p class="card-text"><%= workshop.description %></p>
    <h5 class="card-title">Location</h5>
    <p class="card-text"><%= workshop.location %></p>

    <%= link_to "Check availabilty", workshop, class:"btn btn-success", style:"text-decoration: none;" %>

    <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
  </div>
</div>

app/views/workshops/edit.html.erb
<h1 class="mt-3">Editing <%= @workshop.title %></h1>

<%= render "edit_form", workshop: @workshop %>

app/views/workshops/index.html.erb
<div class="container-fluid p-5 bg-secondary bg-gradient mt-5 mb-5"><h1>Rank Up gives you the opportunity to learn and improve on your gaming. </h1>
<p class="fs-3">Whether it's FPS or MOBA, beginner or expert level, we've got a multitude of gaming workshops created by experienced and passionate instructors to suit your needs. </p>
<p class="fs-3">Come check out the amazing workshops, or even become an instructor yourself.</p>
</div>

<div id="workshops" class ="row">
  <% @workshops.each do |workshop| %>
    <div class="col-md-4">
      <%= render workshop %>
    </div>
  <% end %>
</div>

app/views/workshops/instructor.html.erb
<div class="center mt-3"><h1>Your Workshops</h1></div>

<table class="table table-striped table-bordered">
  <tr>
    <th>Workshop</th>
    <th>Created at</th>
    <th></th>
  </tr>
  <% @workshops.each do |workshop| %>
    <tr>
      <td>
        <%= workshop.title %>
      </td>
      <td>
        <%= workshop.created_at.strftime("%A  %B  %d  %Y %I:%M%p") %>
      </td>
      <td>
        <%= link_to "View", workshop_path(workshop.id), class: "btn btn-primary" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/workshops/new.html.erb
<h1 class="pt-3">Create New Workshop</h1>

<%= render "form", workshop: @workshop %>

app/views/workshops/show.html.erb
<div class="row mt-3 mb-3">
  <div class="col-6">
    <div><p class="badge rounded-pill bg-primary"><%= @workshop.category %></p>
    <p class="badge rounded-pill bg-primary"><%= @workshop.skill_level %></p></div>
    
    <% if @workshop.img.attached? %>
      <%= cl_image_tag(@workshop.img.key, crop: :scale, width: 375, cloud_name: ENV['CLOUDINARY_CLOUD_NAME'])%>
    <% else %>
      <%= cl_image_tag("palceholder_nwndnl.png", crop: :scale, width: 375, cloud_name: ENV['CLOUDINARY_CLOUD_NAME'])%>
    <% end %>
  </div>
  <div class="col-6">
    <h3><%= @workshop.title %></h3>
    <h4>Instructor: <%= @workshop.user.full_name %></h4>
    <p><%= @workshop.description %></p>
  </div>
</div>



<%= link_to "Back", workshops_path, class: "btn btn-primary" %>
<% if user_signed_in? && current_user == @workshop.user %>
  <%= link_to "Edit this workshop", edit_workshop_path(@workshop), class: "btn btn-primary" %>
  <%= link_to "Add more timeslots", new_workshop_timeslot_path(@workshop), class: "btn btn-primary" %>
  <%= button_to("Delete workshop", @workshop, method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete this workshop" }}, type:'button', class: 'btn btn-danger mt-3') %>
<% end %>

<h1 class="mt-3">Time Slots</h1>
<table class="table table-striped table-bordered">
  <tr>
    <th>Day</th>
    <th>Time</th>
    <th>Price</th>
    <th>Remaining Tickets</th>
    <th></th>
  </tr>
  <% @timeslots.each do |timeslot| %>
    <tr>
      <td>
        <%= timeslot.day.strftime("%A  %B  %d  %Y") %>
      </td>
      <td>
        <%= "#{timeslot.start_time.strftime("%I:%M%p")} - #{timeslot.end_time.strftime("%I:%M%p")}" %>
      </td>
      <td>
        <%= number_to_currency(timeslot.price) %>
      </td>
      <td>
        <%= timeslot.available_tickets %>
      </td>
      <% if current_user != @timeslots.first.workshop.user %>
        <td>
        <%= link_to "Book", new_timeslot_booking_path(timeslot.id), class: "btn btn-success" %>
        </td>
      <% else %>
        <td>
        <%= link_to "Edit", edit_timeslot_path(timeslot.id), class: "btn btn-primary mb-2" %>
        <%= button_to "Delete", {controller: :timeslots, action: :destroy, id: timeslot.id}, form: { data: { turbo_confirm: "Are you sure you want to delete this timeslot" }}, method: :delete, type:'button', class: 'btn btn-danger' %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>