config/routes.rb
Rails.application.routes.draw do
  resources :workshops, shallow: true do
    resources :timeslots, shallow: true do
      resources :bookings
    end
  end
  devise_for :users

  get "instructor", to: "workshops#instructor"
  get "sales", to: "bookings#sales"
  get "purchases", to: "bookings#purchases"

  root "workshops#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :timeslot

  belongs_to :instructor, class_name: "User"
  belongs_to :attendee, class_name: "User"
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :eager_load
  before_action :set_booking, only: %i[ show edit update destroy ]
  before_action :set_timeslot, only: %i[ new create ]
  before_action :authenticate_user!

  def sales
    # select bookings where the current user is the instructor
    @bookings = Booking.where(instructor: current_user).order(created_at: :desc)
  end

  def purchases
    # select bookings where the current user is the attendee
    @bookings = Booking.where(attendee: current_user).order(created_at: :desc)
  end

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @timeslot.update_ticket_count
    @booking = Booking.new(booking_params)
    @booking.timeslot_id = @timeslot.id
    @booking.attendee_id = current_user.id
    @booking.instructor_id = @timeslot.workshop.user_id

    respond_to do |format|
      if @booking.save
        format.html { redirect_to root_url, notice: "Booking was successfully created." }
        # format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    def set_timeslot
      @timeslot = Timeslot.find(params[:timeslot_id])
    end

    #eager load associations 
    def eager_load
      @bookings = Booking.includes(:timeslot)
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.fetch(:booking, {}).permit(:timeslot_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
</div>

app/views/bookings/_form.html.erb
<%= form_for([@timeslot, @booking]) do |form| %>
  <% if @booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card text-white bg-secondary mb-3" style="max-width: 18rem;">
    <div class="card-header"><%= @timeslot.workshop.title %></div>
    <div class="card-body">
      
    <p class="card-text">
      <strong>Day: </strong>
      <%= @timeslot.day.strftime("%A  %B  %d  %Y") %>
    </p>

    <p class="card-text">
      <strong>Time: </strong>
      <%= "#{@timeslot.start_time.strftime("%I:%M%p")} - #{@timeslot.end_time.strftime("%I:%M%p")}" %>
    </p>

    <p class="card-text">
      <strong>Price: </strong>
      <%= number_to_currency(@timeslot.price) %>
    </p>

    <p class="card-text">
      <strong>Location:</strong>
      <%= @timeslot.available_tickets %>
    </p>
    </div>

    <div class="d-flex justify-content-between">
      <%= link_to "Back", workshop_path(@timeslot.workshop_id), class:'btn btn-primary' %>
      <%= form.submit 'Confirm Booking', class:'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bookings</h1>

<div id="bookings">
  <% @bookings.each do |booking| %>
    <%= render booking %>
    <p>
      <%= link_to "Show this booking", booking %>
    </p>
  <% end %>
</div>

<%= link_to "New booking", new_booking_path %>

app/views/bookings/new.html.erb
<div class="d-flex justify-content-center mt-3 flex-column align-items-center">
  <h1>Booking Confirmation</h1>
  <%= render "form" %>
</div>

app/views/bookings/purchases.html.erb
<div class="center mt-3"><h1>Purchases History</h1></div>

<table class="table table-striped table-bordered">
  <tr>
    <th>Workshop</th>
    <th>Workshop date</th>
    <th>Timeslot ID</th>
    <th>Instructor</th>
    <th>Booked on</th>
    <th>Amount paid</th>
  </tr>
  <% @bookings.each do |booking| %>
    <tr>
      <td>
        <%= booking.timeslot.workshop.title %>
      </td>
      <td>
        <%= "#{booking.timeslot.day.strftime("%A  %B  %d  %Y")} : #{booking.timeslot.start_time.strftime("%I:%M%p")} - #{booking.timeslot.end_time.strftime("%I:%M%p")}" %>
      </td>
      <td>
        <%= booking.timeslot_id %>
      </td>
      <td>
        <%= booking.instructor.full_name %>
      </td>
      <td>
        <%= booking.created_at.strftime("%A  %B  %d  %Y %I:%M%p") %>
      </td>
      <td>
        <%= number_to_currency(booking.timeslot.price) %>
      </td>

    </tr>
  <% end %>
</table>

app/views/bookings/sales.html.erb
<div class="center mt-3"><h1>Sales History</h1></div>

<table class="table table-striped table-bordered">
  <tr>
    <th>Workshop</th>
    <th>Workshop date</th>
    <th>Timeslot ID</th>
    <th>Booked by</th>
    <th>Booked on</th>
    <th>Amount paid</th>
  </tr>
  <% @bookings.each do |booking| %>
    <tr>
      <td>
        <%= booking.timeslot.workshop.title %>
      </td>
      <td>
        <%= "#{booking.timeslot.day.strftime("%A  %B  %d  %Y")} : #{booking.timeslot.start_time.strftime("%I:%M%p")} - #{booking.timeslot.end_time.strftime("%I:%M%p")}" %>
      </td>
      <td>
        <%= booking.timeslot_id %>
      </td>
      <td>
        <%= booking.attendee.full_name %>
      </td>
      <td>
        <%= booking.created_at.strftime("%A  %B  %d  %Y %I:%M%p") %>
      </td>
      <td>
        <%= number_to_currency(booking.timeslot.price) %>
      </td>

    </tr>
  <% end %>
</table>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @booking %>

<div>
  <%= link_to "Edit this booking", edit_booking_path(@booking) %> |
  <%= link_to "Back to bookings", bookings_path %>

  <%= button_to "Destroy this booking", @booking, method: :delete %>
</div>