config/routes.rb
Rails.application.routes.draw do
  resources :workshops, shallow: true do
    resources :timeslots, shallow: true do
      resources :bookings
    end
  end
  devise_for :users

  get "instructor", to: "workshops#instructor"
  get "sales", to: "bookings#sales"
  get "purchases", to: "bookings#purchases"

  root "workshops#index"
end

app/models/timeslot.rb
class Timeslot < ApplicationRecord
  validates :day, :start_time, :end_time, :price, :available_tickets, presence: true
  validates :price, :available_tickets, numericality: { greater_than: 0 }
  validates :end_time, comparison: { greater_than: :start_time }
  validates :day, comparison: { greater_than: Date.today }

  belongs_to :workshop

  has_many :bookings, dependent: :destroy

  def update_ticket_count
    self.available_tickets -= 1
    self.save
  end
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  before_action :eager_load
  before_action :set_timeslot, only: %i[ show edit update destroy ]
  before_action :set_workshop, only: %i[ index new create ]
  before_action :authenticate_user!, except: %i[index show]

  # GET /timeslots or /timeslots.json
  def index
    # select timeslots belonging to the curent workshop
    @timeslots = Timeslot.all.filter { |e| e.workshop.id == @workshop.id }
  end

  # GET /timeslots/1 or /timeslots/1.json
  def show
  end

  # GET /timeslots/new
  def new
    authorize(@workshop)
    @timeslot = Timeslot.new
  end

  # GET /timeslots/1/edit
  def edit
    authorize(@timeslot)
  end

  # POST /timeslots or /timeslots.json
  def create
    @timeslot = Timeslot.new(timeslot_params)
    @timeslot.workshop_id = @workshop.id

    respond_to do |format|
      if @timeslot.save && params[:save_end]
        format.html { redirect_to timeslot_path(@timeslot.id), notice: "Timeslot was successfully created" }
        format.json { render :show, status: :created, location: @timeslot }
      elsif @timeslot.save && params[:save_continue]
        # sent to a new timeslot page
        format.html { redirect_to new_workshop_timeslot_path(@workshop.id), notice: "Timeslot was successfully created. You can add another one" }
        format.json { render :show, status: :created, location: @timeslot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @timeslot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timeslots/1 or /timeslots/1.json
  def update
    respond_to do |format|
      if @timeslot.update(timeslot_params)
        format.html { redirect_to timeslot_url(@timeslot), notice: "Timeslot was successfully updated." }
        format.json { render :show, status: :ok, location: @timeslot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @timeslot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timeslots/1 or /timeslots/1.json
  def destroy
    
    respond_to do |format|
      format.html { redirect_to workshop_path(@timeslot.workshop.id), notice: "Timeslot was successfully destroyed." }
      format.json { render :no_content }
    end
    @timeslot.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timeslot
      @timeslot = Timeslot.find(params[:id])
    end

    def set_workshop
      @workshop = Workshop.find(params[:workshop_id])
    end

    #eager load associations 
    def eager_load
      @timeslots = Timeslot.includes(:workshop)
      @workshops = Workshop.includes(:user)
    end

    # Only allow a list of trusted parameters through.
    def timeslot_params
      params.require(:timeslot).permit(:workshop_id, :day, :start_time, :end_time, :price, :total_tickets, :available_tickets)
    end
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/timeslots/_form.html.erb
<%= form_for([@workshop, @timeslot]) do |form| %>
  <% if @timeslot.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@timeslot.errors.count, "error") %> prohibited this timeslot from being saved:</h2>

      <ul>
        <% @timeslot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="mb-3">
    <%= form.label :day, class:"form-label" %>
    <%= form.date_field :day, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :start_time, class:"form-label" %>
    <%= form.time_field :start_time, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :end_time, class:"form-label" %>
    <%= form.time_field :end_time, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :price, class:"form-label" %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :available_tickets, class:"form-label" %>
    <%= form.number_field :available_tickets, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Save and finish", name:"save_end", class:"btn btn-primary" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Save and add more timeslots", name:"save_continue", class:"btn btn-primary" %>
  </div>
  
<% end %>

app/views/timeslots/_timeslot.html.erb
<div id="<%= dom_id timeslot %>" class="mt-3 d-flex flex-column align-items-center">
  <div class="card text-white bg-secondary mb-3" style="max-width: 18rem;">
    <div class="card-header"><%= timeslot.workshop.title %></div>
    <div class="card-body">
      
    <p class="card-text">
      <strong>Day: </strong>
      <%= timeslot.day.strftime("%A  %B  %d  %Y") %>
    </p>

    <p class="card-text">
      <strong>Time: </strong>
      <%= "#{timeslot.start_time.strftime("%I:%M%p")} - #{timeslot.end_time.strftime("%I:%M%p")}" %>
    </p>

    <p class="card-text">
      <strong>Price: </strong>
      <%= number_to_currency(timeslot.price) %>
    </p>

    <p class="card-text">
      <strong>Tickets remaining tickets:</strong>
      <%= timeslot.available_tickets %>
    </p>
    </div>
  </div>
</div>

app/views/timeslots/edit.html.erb
<h1>Editing timeslot</h1>

<%= render "form", timeslot: @timeslot %>

<div>
  <%# <%= link_to "Edit this timeslot", edit_timeslot_path(@timeslot.id), class:'btn btn-primary' %> %>
  <%# <%= link_to "Back to timeslots", workshop_timeslots_path(@workshop.id), class:"btn btn-primary" %> %>
  <%# <%= button_to "Destroy this timeslot", @timeslot, method: :delete, class:'btn btn-danger mt-3' %> %>
</div>

app/views/timeslots/index.html.erb
<h1 class="mt-3 mb-3">Timeslots for <%= @workshop.title %></h1>

<div id="timeslots" class="row">
  <% @timeslots.each do |timeslot| %>
    <div class="col-md-4">
      <div class='d-flex flex-column align-items-center'>
        <%= render timeslot %>
        <div>
          <%= link_to "Edit this timeslot", edit_timeslot_path(timeslot.id), class:'btn btn-primary mb-2' %>
          <%= button_to "Destroy this timeslot", timeslot, method: :delete, class:'btn btn-danger' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/timeslots/new.html.erb
<h1 class="mt-3"><%= "Add new timeslot for #{@workshop.title}" %></h1>

<%= render "form" %>

<div>
  <%= link_to "Back", workshop_path(@workshop.id), class:"btn btn-primary" %>
</div>

app/views/timeslots/show.html.erb
<div class="d-flex align-items-center flex-column">
  <%= render @timeslot %>
  <div>
    <%= link_to "Back to workshop", workshop_path(@timeslot.workshop.id), class:"btn btn-primary" %>
    <%= link_to "Edit this timeslot", edit_timeslot_path(@timeslot.id), class:'btn btn-primary' %>
    <%= button_to "Destroy this timeslot", @timeslot, method: :delete, class:'btn btn-danger mt-3' %>
  </div>
</div>